# Generated by Django 3.0.10 on 2020-09-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_mobile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mobile phone number'),
            preserve_default=False,
        ),
    ]
