# Generated by Django 3.0.10 on 2020-09-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200910_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mobile phone number (format: 41798257004)'),
        ),
    ]
