# Generated by Django 3.0.10 on 2020-09-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waateaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availbility',
            name='state',
            field=models.IntegerField(choices=[(0, 'Not set'), (1, 'Dont know'), (2, 'Unavailable'), (3, 'Available')], default=0),
        ),
    ]
