# Generated by Django 3.0.10 on 2020-09-09 21:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waateaapp', '0002_availbility_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availbility',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
        migrations.CreateModel(
            name='Gameday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('games', models.ManyToManyField(to='waateaapp.Game')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waateaapp.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='availbility',
            name='gameday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waateaapp.Gameday'),
        ),
    ]
